application: redirect-io
version: 2015111001
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  max_idle_instances: 5
  max_pending_latency: 3s

builtins:
- remote_api: on

libraries:
- name: markupsafe
  version: latest
- name: endpoints
  version: latest
- name: lxml
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: run.app